### ISSUE TITLE
from pydoro.pydoro_core.tomato import Tomato ImportError: No module named pydoro_core.tomato

### ISSUE THREAD

**Issue by 0xj4f** [JaDogg/pydoro#159]
My error
```
Traceback (most recent call last):
  File "/Users/<USER>/Library/Python/2.7/bin/pydoro", line 5, in <module>
    from pydoro.pydoro import main
  File "/Users/<USER>/Library/Python/2.7/lib/python/site-packages/pydoro/pydoro.py", line 15, in <module>
    from pydoro.pydoro_core.tomato import Tomato
ImportError: No module named pydoro_core.tomato
```

I just installed the software using the instructions

```
 pip install pydoro
 pydoro
```

Then add to $PATH

**Comment by JaDogg** [comment]
@codeandrew sorry for the delay in responding. Try with Python 3.6+. It seems you tried this with Python 2.7. Which is not supported as mentioned in the README.md. :)
