### ISSUE TITLE
Unecessary msilib import

### ISSUE THREAD

**Issue by gmelodie** [JaDogg/pydoro#332]
While building the project locally for development I found that commenting out [this line](https://github.com/JaDogg/pydoro/blob/develop/pydoro/pydoro_tui.py#L7) from `pydoro_tui.py` made `pydoro` work on Linux, while before it was giving me:

```bash
(venv) ➜  pydoro git:(master) pydoro
Traceback (most recent call last):
  File "/home/gmelodie/.local/bin/pydoro", line 33, in <module>
    sys.exit(load_entry_point('pydoro', 'console_scripts', 'pydoro')())
  File "/home/gmelodie/.local/bin/pydoro", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gmelodie/repos/pydoro/pydoro/pydoro_tui.py", line 7, in <module>
    from msilib.schema import EventMapping
ModuleNotFoundError: No module named 'msilib'
```

I noticed that nothing is using `EventMapping`. Maybe we'd want to comment it out?

**Comment by JaDogg** [comment]
Actually there seem to be few more unwanted imports there hmm

**Comment by JaDogg** [comment]
Got rid of, seems like I missed this in a review and someone accidently added some imports. @gmelodie  thanks for catching it :)
