### ISSUE TITLE
Install with pipx under 3.12.3 will not run

### ISSUE THREAD

**Issue by ssteinerx** [JaDogg/pydoro#344]
**Install**
```bash
ssteiner@B450M-DS3H:~
$ pipx install pydoro
  installed package pydoro 0.2.3, installed using Python 3.12.3
  These apps are now globally available
    - pydoro
done! ✨ 🌟 ✨
```
**Run, crash**
```bash
ssteiner@B450M-DS3H:~
$ pydoro
Traceback (most recent call last):
  File "/home/ssteiner/.local/pipx/venvs/pydoro/lib/python3.12/site-packages/pydoro/pydoro_core/util.py", line 17, in in_app_path
    wd = sys._MEIPASS
         ^^^^^^^^^^^^
AttributeError: module 'sys' has no attribute '_MEIPASS'
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Kubuntu 24.04

**Comment by thairanaru** [comment]
I can replicate using Python 3.12.4 on Fedora Linux 40

**Comment by 47ronin** [comment]
Error replicated in macOS Sonoma 14.6.1 using pipx

**Comment by shayan15sa** [comment]
I can replicate using pipx 1.4.3 python 3.12.3 linux mint 22 too.

Full error:
pygame 2.6.0 (SDL 2.28.4, Python 3.12.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/shayan/.local/share/pipx/venvs/pydoro/lib/python3.12/site-packages/pydoro/pydoro_core/util.py", line 17, in in_app_path
    wd = sys._MEIPASS
         ^^^^^^^^^^^^
AttributeError: module 'sys' has no attribute '_MEIPASS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shayan/.local/bin/pydoro", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/shayan/.local/share/pipx/venvs/pydoro/lib/python3.12/site-packages/pydoro/pydoro_tui.py", line 127, in main
    config = Configuration()
             ^^^^^^^^^^^^^^^
  File "/home/shayan/.local/share/pipx/venvs/pydoro/lib/python3.12/site-packages/pydoro/pydoro_core/config.py", line 14, in __init__
    self._cli_load()
  File "/home/shayan/.local/share/pipx/venvs/pydoro/lib/python3.12/site-packages/pydoro/pydoro_core/config.py", line 142, in _cli_load
    self.audio_file = self.cli_args.audio_file or self.audio_file or in_app_path("b15.wav")
                                                                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shayan/.local/share/pipx/venvs/pydoro/lib/python3.12/site-packages/pydoro/pydoro_core/util.py", line 20, in in_app_path
    return _from_resource(path)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/shayan/.local/share/pipx/venvs/pydoro/lib/python3.12/site-packages/pydoro/pydoro_core/util.py", line 24, in _from_resource
    from pkg_resources import resource_filename
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by XX3E** [comment]
Hi,
i had the same problem. Here is a fix which is working for me:

https://github.com/JaDogg/pydoro/pull/348/files
